version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: vend-postgres
    environment:
      POSTGRES_DB: vend_assessment
      POSTGRES_USER: vend
      POSTGRES_PASSWORD: vend_dev_pass
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U vend']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

